<a href="https://colab.research.google.com/github/pierre-mazard/philomathia/blob/main/Philomathia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Philomathia


Sommaire :
* Algèbre linéaire
* Probabilités et Statistique
* Calcul de dérivée
* Aller plus loin...

**Pourquoi Python pour les mathématiques ?**

Le langage Python est un langage généraliste, offrant des bibliothèques puissantes en calcul numérique (NumPy, SciPy, SymPy, Matplotlib,...), facilitant les opérations mathématiques plus ou moins complexes, l'analyse statistique et la visualisation des données. Son interactivité via des environnements comme Jupyter Notebook favorise un processus de développement itératif.
La communauté active de développeurs et les nombreuses ressources en ligne font de Python un outil incontournable.

**Pourquoi ce projet ?**

Dans ce projet, nous allons aborder des notions de mathématiques basiques nécessaires à la prochaine Unit, le Machine Learning. Pas de panique, nous n'allons rien inventer, nous allons simplement utiliser Python afin de manipuler des vecteurs, des matrices, des probabilités, des graphes faire des simulations et d'autres calculs sympatiques !

\

**Il n'est bien sûr pas question d'apprendre par coeur les notions apprises dans ce sujet, mais de s'en servir comme un guide pour d'éventuels futurs questionnements.**

\

**Merci de lire et de répondre attentivement aux questions ci-dessous. Appuyez-vous sur les ressources de la base de connaissances.**

# Librairies utilisées

In [2]:
import numpy as np
import pandas as pd
import sympy as sp
from fractions import Fraction

import matplotlib.pyplot as plt

from sklearn.datasets import load_wine

# Algèbre linéaire
Vous devrez exclusivement utiliser la librairie `numpy` dans la section suivante.

## **Job 0**

1. Créez le vecteur ligne $v = (4, 1, 9)$
2. Additionnez, multipliez et divisez le vecteur $v$ par $2$  



In [3]:
v = np.array([4,1,9])
v, v.shape

(array([4, 1, 9]), (3,))

In [4]:
v_add = v + 2
v_add, v_add.shape

(array([ 6,  3, 11]), (3,))

In [5]:
v_mul = v * 2
v_mul, v_mul.shape

(array([ 8,  2, 18]), (3,))

In [6]:
v_div = v / 2
v_div, v_div.shape

(array([2. , 0.5, 4.5]), (3,))

--------------------------------------------------------------------------------


## **Job 1**
Additionnez le vecteur $v$ avec le vecteur $w$, définie comme suit $w = (-1, -1, 0)$

In [7]:
w = np.array([-1,-1,0])
v_add_w = v + w

v_add_w, v_add_w.shape

(array([3, 0, 9]), (3,))

-----------------------------------------------------------------

## **Job 2**
Soient les matrices $M$ et $N$ définies comme suit :
$$M = \begin{pmatrix}
1 & 2  \\
5 & 6
\end{pmatrix},\space N = \begin{pmatrix}
1 & 1 & -1  \\
0 & 0 & 1
\end{pmatrix} $$

1. Créez les matrices $M$ et $N$. Quelles sont les dimensions de chacune ? Sont-elles des matrices carrées ?
2. Est-il possible d'additionner $M$ et $N$ ? Justifiez. Si oui, calculez l'addition.
3. Est-il possible de faire le produit matriciel de M par N ? Justifiez. Si oui, calculez le produit.



In [8]:
M = np.array(([1, 2], [5, 6]))
N = np.array(([1, 1, -1], [0, 0, 1]))

In [9]:
M, M.shape

(array([[1, 2],
        [5, 6]]),
 (2, 2))

In [10]:
N, N.shape

(array([[ 1,  1, -1],
        [ 0,  0,  1]]),
 (2, 3))

(M) est une matrices carrée car elle est de dimension n * n. 

(N) n'est pas une matrice carrée car elle n'est pas de dimension n * n. 

Pour additionner deux matrices, il faut qu'elles aient la même dimension. (M) et (N) ont des dimensions différentes (M dim(2, 2)) et (N dim(2, 3), il n'est pas possible de les additionner. 

Pour faire le produit de deux matrices (A) et (B), le nombre de colones de (A) doit être égal au nombre de lignes de (B).
Ici (M) à deux lignes et (B) deux colones, on peut donc les multiplier.

In [11]:
produit_MN = np.dot(M, N)
produit_MN, produit_MN.shape

(array([[1, 1, 1],
        [5, 5, 1]]),
 (2, 3))

-----------------------------------

## **Job 3**
Soit la matrice suivante :
$$A = \begin{pmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{pmatrix} $$

1. Créez et affichez la matrice A

2. Créez une copie $C$ de la matrice $A$

3. Créez une copie superficielle $B$ de la matrice $A$, sans copier sa référence

4. Affichez la valeur se trouvant à la ligne 2 et à la colonne 3

5. Affichez tous les éléments de la $2^{ème}$ ligne

6. Affichez tous les éléments de la $1^{ème}$ colonne

7. Affichez la diagonale de $A$

8. Multipliez la matrice $A$ par $\frac{1}{2}$

In [12]:
A = np.array(([1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]))
A, A.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 (4, 4))

In [13]:
C = A.copy()
C, C.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 (4, 4))

In [14]:
B = A.view()
B, B.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 (4, 4))

In [15]:
valeur_1_2 = A[1, 2]
valeur_1_2

7

In [16]:
ligne_2 = A[1, :]
ligne_2

array([5, 6, 7, 8])

In [17]:
colonne_1 = A[:, 0]
colonne_1

array([ 1,  5,  9, 13])

In [18]:
diagonale = np.diag(A)
diagonale

array([ 1,  6, 11, 16])

In [19]:
A_multiplie = A * 0.5
A_multiplie

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ],
       [6.5, 7. , 7.5, 8. ]])

## **Job 4**
Considérons les matrices $A$ et $A_{bis}$ définies comme ci-dessous :

$$ A = \begin{pmatrix}
1 & 5 & 3  \\
2 & 4 & 7
\end{pmatrix}, \space A_{bis} = \begin{pmatrix}
1 & 2  \\
5 & 4 \\
3 & 7
\end{pmatrix}$$

1. Quelles sont les dimensions de $A$ et de $A_{bis}$ ?
2. Qu'est ce que vous voyez en observant ces deux matrices ?
3. Quelle opération mathématique permet d'obtenir $A_{bis}$ comme résultat à partir de $A$ ?
4. Quelle fonction Python permet de faire ce type d'opération ?
5. A l'aide de l'opération précédente, transformez les vecteurs et les matrices ci-dessous. Affichez leurs dimensions avant et après l'opération :
  * $\begin{pmatrix}
7  \\
4 \\
1
\end{pmatrix}$

  * $\begin{pmatrix}
9 & 0 & 3 \\
\end{pmatrix}$

  * $\begin{pmatrix}
2 & 4 & 1 \\
0 & 5 & 2 \\
3 & 1 & 6
\end{pmatrix}$

  * $\begin{pmatrix}
  7 & 2 & 5 & 1 \\
3 & 6 & 0 & 2 \\
\end{pmatrix}$


La matrice (A) est de dimension 2 par 3.

La matrice (Abis) est de dimension 3 par 2.

La matrice Abis est la transposée de la matrice A : (A^T = Abis). Abis est obtenue en échangeant les lignes et les colonnes de A.  

L'opération mathématique permetant d'obtenir Abis à partir de A est la transposition : (A^T)ij = Aij

In [20]:
A = np.array(([1, 5, 3], [2, 4, 7]))
Abis = A.T 
Abis

array([[1, 2],
       [5, 4],
       [3, 7]])

In [21]:
A = np.array(([7], [4], [1]))
Abis = A.T

A, A.shape, Abis, Abis.shape


(array([[7],
        [4],
        [1]]),
 (3, 1),
 array([[7, 4, 1]]),
 (1, 3))

In [22]:
A = np.array([9, 0, 3])
Abis = A.reshape(3, 1)

A, A.shape, Abis, Abis.shape

(array([9, 0, 3]),
 (3,),
 array([[9],
        [0],
        [3]]),
 (3, 1))

In [23]:
A = np.array(([2, 4, 1], [0, 5, 2], [3, 1, 6]))
Abis = A.T

A, A.shape, Abis, Abis.shape

(array([[2, 4, 1],
        [0, 5, 2],
        [3, 1, 6]]),
 (3, 3),
 array([[2, 0, 3],
        [4, 5, 1],
        [1, 2, 6]]),
 (3, 3))

In [24]:
A = np.array(([7, 2, 5, 1], [3, 6, 0, 2]))
Abis = A.T

A, A.shape, Abis, Abis.shape

(array([[7, 2, 5, 1],
        [3, 6, 0, 2]]),
 (2, 4),
 array([[7, 3],
        [2, 6],
        [5, 0],
        [1, 2]]),
 (4, 2))

------------------------------------------

## **Job 5**
On considère la matrice $A$ de dimension 3 $\times 4$ définie comme :

$$ A = \begin{pmatrix}
4 & 6 & -2 & 3 \\
2 & -1 & 0 & 1 \\
-7 & 0 & 1 & 12
\end{pmatrix} $$

1. Créez la matrice $A$.

2. Modifiez la matrice $A$ pour que ses deux premières lignes soient multipliées par 2 et que sa dernière colonne soit divisée par 3.

3. Créez une nouvelle matrice $B$ définie comme :

$$ B = \begin{pmatrix}
4 & 5 & 6 \\
5 & 10 & 15 \\
1 & 1 & 1
\end{pmatrix}  $$

4. Réalisez le produit matriciel de $B$ et $A$, notez le $D$.

In [25]:
A = np.array(([4, 6, -2, 3], [2, -1, 0, 1], [-7, 0, 1, 12]))
A[:2, :] = A[:2, :] * 2
A[:, -1] = A[:, -1] / 3
A


array([[ 8, 12, -4,  2],
       [ 4, -2,  0,  0],
       [-7,  0,  1,  4]])

In [26]:
B = np.array(([4, 5, 6], [5, 10, 15], [1, 1, 1]))
D = np.dot(B, A)
A, B, D

(array([[ 8, 12, -4,  2],
        [ 4, -2,  0,  0],
        [-7,  0,  1,  4]]),
 array([[ 4,  5,  6],
        [ 5, 10, 15],
        [ 1,  1,  1]]),
 array([[ 10,  38, -10,  32],
        [-25,  40,  -5,  70],
        [  5,  10,  -3,   6]]))

---------------------------------------------------------

## **Job 6**

Soit la matrice $I_3$ définie comme suit :
$$ \begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}$$

1. Faites une multiplication matricielle de $I_3$ et d'une autre matrice de même taille de votre choix. Qu'est ce que vous observez ?
2. Renseignez-vous sur la matrice $I_3$. Quelles sont ses caractéristiques ?

In [27]:
I3 = np.eye(3)
I4 = np.array(([2, 4, 1], [6, 2, 9], [1, 4, 0]))
I5 = np.dot(I3, I4)
I5, I5.shape

(array([[2., 4., 1.],
        [6., 2., 9.],
        [1., 4., 0.]]),
 (3, 3))

I3 est une matrice identée symétrique (A = A^T), ce qui signifie qu'elle est égale à sa transposée. 

Le produit d'une matrice identitée A avec une matrice B sera toujours égal à B. 

Donc ici I3 * I4 = I4. 


--------------------------------------------------------------

## **Job 7**

Pour un nombre réel $x$, son inverse, noté $\frac{1}{x}$ ou $x^{-1}$, est un autre nombre tel que $x \times \frac{1}{x} = 1$

 En d'autres termes, lorsque vous multipliez un nombre par son inverse, le résultat est toujours $1$.

 Démontrez le dans la cellule ci-dessous pour des nombres de votre choix.

In [28]:
# Pour tous réels x, x = x/1 ou bien x = x^1
# Or l'inverse de x/1 = 1/x ou bien l'inverse de x^1 est x^-1 
# Donc l'inverse de x est 1/x ou bien x^-1 et le produit de x par son inverse est 1 car 1/x * x/1 = 1
x = 158
x_inv = 1/x
x * x_inv

1.0

-----------------------------------------------------------------

## **Job 8**

L'inverse d'une matrice est une autre matrice qui, lorsqu'elle est multipliée par la matrice d'origine, donne une matrice identité. En d'autres termes, si $A$ est une matrice et $A^{-1}$ est son inverse, alors $A \times A^{-1} = I$.

*(C'est comme si l'inverse de la matrice "compensait" les effets de la matrice d'origine, de la même manière que l'inverse d'un nombre "compense" sa multiplication initiale pour obtenir $1$.)*

Soient deux matrices $A$ et $B$ telles que :

$$ A = \begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}, \space B = \begin{pmatrix}
-2 & 1 \\
1.5 & -0.5
\end{pmatrix}$$

1. Calculez $A \times B$ puis $B \times A$.
2. Que pouvez-vous conclure sur les deux matrices ?

In [29]:
A = np.array(([1, 2], [3, 4]))
B = np.array(([-2, 1], [1.5, -0.5]))
A_mult_B = np.dot(A, B)
B_mult_A = np.dot(B, A)
A_mult_B, B_mult_A

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [0., 1.]]))

En observant les résultats on remarque qu'ils forment tous les deux des matrices identité parfaites, ce qui signifie qu'elles sont exactement ce que l'on espère ibtenir en mutlipliant une matrice par son inverse ou bien lorsque l'on multiplie deux patrices qui sont inverses l'une de l'autre dans un certain ordre. 

Donc la matrice (B) est l'inverse de la matrice (A)


----------------------------------------------------------------------

## **Job 9**

On dit qu'une matrice carrée $M$ est inversible (ou possède un inverse $M^{-1}$) si son déterminant $det(M)\neq 0$.

**Par exemple :**

$$ M = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}, \space det(M) = (a \times d) - (c \times b) \neq 0$$

On définit alors $M^{-1}$ comme suit :

$$ M^{-1} = \frac{1}{det(M)} \times \begin{pmatrix}
d & -b \\
-c & a
\end{pmatrix} $$

\

1. Vérifiez si les matrices carrées ci-dessous sont inversibles (il existe une fonction de numpy qui le fait très bien...) :

  * $ \begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}$

  * $ \begin{pmatrix}
3 & 2 \\
4 & 1
\end{pmatrix}$

  * $ \begin{pmatrix}
1 & 5 \\
7 & 8 \\
0 & 1
\end{pmatrix}$

  * $ \begin{pmatrix}
1 & 2 & 3 \\
0 & -1 & 4 \\
2 & 1 & 5
\end{pmatrix}$


2. Calculez l'inverse de ces matrices à l'aide de la formule donnée précédemment.

-----------------------------------------------------------------

# Probabilités et Statistique

## **Job 10**
**La probabilité d'un événement est un nombre réel compris entre 0 et 1. Plus ce nombre est grand, plus le risque, ou la chance, que l'événement se produise est grand.**

Lancez une pièce de monnaie 100 fois et enregistrez le résultat, pile ou face, dans un `array` $T$.
1. Quelle est donc la probabilité d'obtenir le résultat Pile ou le résultat Face ?
3. Visualisez la proportion des résultats à l'aide d'un piechart de `Matplotlib` (ou d'une autre librairie de votre choix).


## **Job 11**

Considérez un dé $D_6$ dont les valeurs possibles sont : $\{1, 2, 3, 4, 5, 6\}$.

Ce dé est non truqué, ce qui signifie que toutes les valeurs ont des probabilités égales de se produire.  

Si je jette le dé $D_6$, la probabilité que le résultat soit $3$ est de $\frac{1}{6}$.

1. Quelle est la probabilité d'obtenir $7$ au jet du dé $D_6$ ?
2. Quelle est la probabilité d'obtenir un résultat pair ?
3. Quelle est la probabilité d'obtenir un résultat impair ?
4. Quelle est la probabilité d'obtenir un résultat inférieur ou égal à $4$ ?
5. Quelle est la probabilité d'obtenir un résultat inférieur ou égal à $6$ ?
6. Quelle est la probabilité de ne pas obtenir $1$ ?

-------------------------------------------------------------

## **Job 12**
A l'aide de `numpy` et de ses différentes fonctions :
* Créez un vecteur ligne $R$ de taille $n=450$ composé de nombres naturels entre $0$ et $9$ générés aléatoirement
* Calculez la valeur moyenne du tableau
* Calculez la valeur médiane
* Calculez la variance
* Calculez l'écart-type

----------------------------------------------

## **Job 13**
A l'aide de matplotlib (ou d'une autre librairie de votre choix), visualisez la distribution des données du tableau $R$ en générant un histogramme.

---------------------------------------------------------

## **Job 14**
A l'aide de matplotlib (ou d'une autre librairie de votre choix), visualisez la distribution et dispersion des données du tableau $R$ à travers leurs **quartiles** en utilisant l'outil statistique, le boxplot.

-----------------------------------------------------

## **Job 15**

Considérons des données de résultats d'une analyse chimique de vins cultivés en Italie issus de trois cultivars différents. Ces données ont été récupérées et chargées dans un `DataFrame` via la code ci-dessous.

1. Affichez différentes informations de `wine_df` (nombre d'observations, nombre de caractéristiques, type de données, données manquantes, mémoire allouée en RAM).

2. A l'aide d'une fonction spécifique de `Pandas`, générez les statistiques descriptives (moyenne, médiane, maximum, ...) du jeu de données. Qu'est ce que vous observez ?

3. Visualisez la distribution des différentes variables du jeu de données à l'aide d'un histogramme et d'un boxplot.

4. A l'aide d'une fonction spécifique de `Pandas`, calculez la corrélation linéaire de Pearson par paire des variables.


In [30]:
wine_data = load_wine()

wine_df = pd.DataFrame(data=wine_data.data, columns=wine_data.feature_names)
wine_df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

-------------------------------------------

## Job 16
Une loi de probabilité décrit le comportement aléatoire d'un phénomène dépendant du hasard tels que les lancers de pièces, les dés, les jeux de cartes, et d'autres événements plus complexes.

Considérons la Loi Normale, l'unes des plus importantes en probabilités et en statistique. Les lois normales sont parmi les lois de probabilité les plus utilisées pour modéliser des phénomènes naturels issus de plusieurs événements aléatoires. Elle est caractérisée par sa forme en cloche symétrique.

**Simulez la Loi Normale $\mathcal{N}(0, 1)$ où la moyenne est $0$ et l'écart-type est $1$ :**
1. Générez des échantillons à partir de la distribution normale en utilisant la fonction `np.random.normal`

2. Affichez l'histogramme des données

3. Tracez la courbe de densité de probabilité théorique de $\mathcal{N}(0, 1)$ en traçant la fonction $f(x)$ ci-dessous :

$$ f(x) = \frac{1}{1 \sqrt{2\pi}} \times e^{-\frac{1}{2} \times x^2 }$$

----------------------------------

# Calcul de dérivée

## Job 17

En mathématiques, la dérivée d'une fonction d'une variable réelle mesure l'ampleur du changement de la valeur de la fonction (valeur de sortie) par rapport à un petit changement de son argument (valeur d'entrée). Les calculs de dérivées sont un outil fondamental du calcul infinitésimal. Par exemple, la dérivée de la position d'un objet en mouvement par rapport au temps est la vitesse (instantanée) de l'objet.

\

Calculez la dérivée des fonctions suivantes à l'aide la librairie `SymPy` :

1. $f(x) = 3x^2 - 2x + 5$

2. $g(x) = \frac{2}{x^2}$

3. $h(x) = \sqrt{3x - 1}$

4. $k(x) = e^{x}$

5. $l(x) = ln(x)$

6. $p(x) = \sqrt{x} + 2x^3$

7. $q(x) = sin(x)$

8. $r(x) = \frac{x^2 + 1}{x-1}$

----------------------------------------------------------------------

# Toujours plus loin...

## **Job Bonus 1**
A l'aide de ce que vous avez appris dans le *job 16*, réalisez une simulation du **Théorème Central Limit**.

*Pour des raisons d'organisation et de lisibilité de votre notebook, créez votre implémentation dans des fichiers .py que vous viendrez appeler à l'aide de la cellule ci-dessous :*

----------------------------------------------------------------------

## **Job Bonus 2**

**Un algorithme de tri, notion fondamentale en informatique ou en mathématiques, est un algorithme qui permet d'organiser une collection d'objets selon une relation d'ordre déterminée. Suivant la relation d'ordre considérée, une même collection d’objet peut donner lieu à divers arrangements.**

Par exemple, on pourrait trier un tableau `tab` d'entiers naturels de $1$ à $N$ dans un ordre croissant ou décroissant.

L'implémentation des algorithmes de tri est un excellent exercice pour comprendre des concepts fondamentaux de la programmation, comprendre d'autres algorithmes et se préparer à des entretiens techniques.

Tentez d'implémenter un ou plusieurs des algorithmes de tri suivants :

* **Tri à bulles (bubble sort)**
* **Tri par insertion (Insertion sort)**
* **Tri fusion (merge sort)**
* **Tri rapide (quick sort)**



*Pour des raisons d'organisation et lisibilité de votre notebook, créez vos différentes implémentations des algorithmes de tri dans des fichiers .py que vous viendrez appeler à l'aide de la cellule ci-dessous :*

In [31]:
# Example of a list to be sorted - feel free to try something else!

input_list = [64, 34, 25, 12, 22, 11, 90]

print("This is my original list:", input_list)

# Tri de la list à l'aide d'un algorithme donné - ?
sorted_list = some_sorting_alg(input_list)

print("This is my sorted list:", sorted_list)

This is my original list: [64, 34, 25, 12, 22, 11, 90]


NameError: name 'some_sorting_alg' is not defined